server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Tamaños de payload razonables (subidas, si las hubiera)
  client_max_body_size 20m;
  sendfile on;

  # Gzip simple
  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  # Archivos estáticos con caché
  location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
    expires 30d;
    access_log off;
    try_files $uri =404;
  }

  # Fallback para SPA (React/Vite/Next export)
  location / {
    try_files $uri $uri/ /index.html;
  }

  error_page 404 /404.html;
  location = /404.html {
    internal;
  }
}
